openapi: 3.1.0
info:
  title: MY Projects REST API
  description: API specs for building MY projects.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1 # 나중에 수정
tags:
  - name: Artworks
    description: 팬아트 작품 관리와 관련된 오퍼레이션
paths:
  /artworks:
    $ref: "./paths/artworks.yaml"
  /artworks/images:
    $ref: "./paths/artworks-images.yaml"
