openapi: 3.0.3
info:
  title: MY Projects REST API
  description: API specs for building MY projects.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1

paths:
  /artworks:
    $ref: "./paths/artworks.yaml"
