ErrorBase:
  type: object
  required:
    - code
    - message
  properties:
    code:
      type: string
      description: 에러 식별자
    message:
      type: string
      description: 에러 메시지
    errors:
      type: object
      description: 상세 에러 정보
      additionalProperties:
        type: array
        items:
          type: string
