# 리퀘스트, 리스폰스에 공통적으로 사용될 속성들
ArtworkBase:
  type: object
  properties:
    title:
      type: string
      description: 게임 제목
    imageUrl:
      type: string
      format: uri
      description: 팬아트 작품 이미지 URL
    createdAt:
      type: string
      format: date-time
      description: 팬아트 작품을 완성한 날짜
    playedOn:
      type: string
      enum: [Steam, Switch, GOG, Epic Games, Android]
      description: 플레이한 플랫폼
    rating:
      type: integer
      minimum: 0
      maximum: 20
      description: 개인적으로 매긴 게임 평점 (0-20 정수)
    shortReview:
      type: string
      description: 플레이 후 한줄평
