name: Check OpenAPI specs

on:
  push:
    paths:
      - "openapi/**/*.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check api spec files
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: "openapi/openapi.yaml"
